// Mock data for UI rendering (replace with Prisma in production)

export const SERVICES = [
  {
    id: "s1",
    name: "Knotless Braids",
    slug: "knotless-braids",
    category: "HAIR",
    icon: "💇‍♀️",
    basePrice: 12000,
    minPrice: 10000,
    maxPrice: 25000,
    durationMins: 240,
    description: "Knotless box braids — small, medium, or large.",
    isPopular: true,
  },
  {
    id: "s2",
    name: "Box Braids",
    slug: "box-braids",
    category: "HAIR",
    icon: "💇‍♀️",
    basePrice: 8500,
    minPrice: 7000,
    maxPrice: 18000,
    durationMins: 180,
    description: "Classic box braids in all sizes.",
    isPopular: true,
  },
  {
    id: "s3",
    name: "Weave Installation",
    slug: "weave",
    category: "HAIR",
    icon: "💇‍♀️",
    basePrice: 15000,
    minPrice: 12000,
    maxPrice: 35000,
    durationMins: 150,
    description: "Full weave installation — sew-in or glue-in.",
    isPopular: false,
  },
  {
    id: "s4",
    name: "Full Glam Makeup",
    slug: "full-glam",
    category: "MAKEUP",
    icon: "💄",
    basePrice: 20000,
    minPrice: 15000,
    maxPrice: 50000,
    durationMins: 90,
    description: "Full glam beat for events and special occasions.",
    isPopular: true,
  },
  {
    id: "s5",
    name: "Natural / Soft Glam",
    slug: "soft-glam",
    category: "MAKEUP",
    icon: "💄",
    basePrice: 12000,
    minPrice: 8000,
    maxPrice: 25000,
    durationMins: 60,
    description: "Clean, everyday natural makeup.",
    isPopular: false,
  },
  {
    id: "s6",
    name: "Gel Nails",
    slug: "gel-nails",
    category: "NAILS",
    icon: "💅",
    basePrice: 8000,
    minPrice: 6000,
    maxPrice: 15000,
    durationMins: 90,
    description: "Gel overlay or tips — any design.",
    isPopular: true,
  },
  {
    id: "s7",
    name: "Acrylic Nails",
    slug: "acrylic-nails",
    category: "NAILS",
    icon: "💅",
    basePrice: 10000,
    minPrice: 8000,
    maxPrice: 20000,
    durationMins: 90,
    description: "Full acrylic set — any design.",
    isPopular: false,
  },
  {
    id: "s8",
    name: "Haircut & Fade",
    slug: "fade",
    category: "BARBING",
    icon: "✂️",
    basePrice: 4000,
    minPrice: 3000,
    maxPrice: 8000,
    durationMins: 45,
    description: "Fresh cut with skin or tapered fade.",
    isPopular: true,
  },
  {
    id: "s9",
    name: "Lash Extensions",
    slug: "lash-extensions",
    category: "LASHES",
    icon: "👁️",
    basePrice: 12000,
    minPrice: 10000,
    maxPrice: 25000,
    durationMins: 90,
    description: "Classic or volume lash extensions.",
    isPopular: false,
  },
  {
    id: "s10",
    name: "Volume Lashes",
    slug: "volume-lashes",
    category: "LASHES",
    icon: "👁️",
    basePrice: 18000,
    minPrice: 15000,
    maxPrice: 35000,
    durationMins: 120,
    description: "Volume or mega-volume lash sets.",
    isPopular: false,
  },
];

export const CATEGORIES = [
  { key: "HAIR", label: "Hair", icon: "💇‍♀️", count: 6 },
  { key: "MAKEUP", label: "Makeup", icon: "💄", count: 3 },
  { key: "NAILS", label: "Nails", icon: "💅", count: 3 },
  { key: "BARBING", label: "Barbing", icon: "✂️", count: 3 },
  { key: "LASHES", label: "Lashes", icon: "👁️", count: 3 },
  { key: "SKINCARE", label: "Skincare", icon: "✨", count: 2 },
];

export const GROOMERS = [
  {
    id: "g1",
    name: "Chidinma Adeyemi",
    slug: "chidinma-adeyemi",
    avatar: null,
    initials: "CA",
    headline: "Master braider & hair stylist · 5 years experience",
    specialties: ["Knotless Braids", "Box Braids", "Weaves"],
    categories: ["HAIR"],
    zones: ["Victoria Island", "Lekki", "Ikoyi"],
    avgRating: 4.9,
    reviewCount: 247,
    totalJobs: 389,
    isOnline: true,
    isVerified: true,
    bio: "I specialise in protective styles and have been doing hair professionally since 2019. I bring all supplies — just give me your space and I'll transform your look.",
    baseRate: 12000,
    services: [
      { name: "Knotless Braids", price: 12000, duration: "3–4 hrs" },
      { name: "Box Braids", price: 8500, duration: "2.5–3 hrs" },
      { name: "Ghana Braids", price: 9000, duration: "2–3 hrs" },
      { name: "Weave Install", price: 15000, duration: "2–2.5 hrs" },
    ],
    reviews: [
      {
        author: "Temi A.",
        rating: 5,
        text: "Absolutely love my knotless braids! Chidinma was professional, on time, and her work is flawless.",
        date: "2 days ago",
      },
      {
        author: "Bola O.",
        rating: 5,
        text: "Best braider in Lagos. She showed up exactly when she said she would and my hair looks amazing.",
        date: "1 week ago",
      },
      {
        author: "Amaka N.",
        rating: 5,
        text: "Very fast and neat. My knotless braids lasted 3 months!",
        date: "2 weeks ago",
      },
    ],
  },
  {
    id: "g2",
    name: "Shade Martins",
    slug: "shade-martins",
    avatar: null,
    initials: "SM",
    headline: "MUA & skincare specialist · Glam & natural looks",
    specialties: ["Full Glam", "Soft Glam", "Bridal"],
    categories: ["MAKEUP"],
    zones: ["Lekki", "VI", "Oniru"],
    avgRating: 4.7,
    reviewCount: 183,
    totalJobs: 271,
    isOnline: true,
    isVerified: true,
    bio: "I am a trained MUA with experience in glam, natural, and bridal looks. I use only premium products and carry my full kit to every booking.",
    baseRate: 20000,
    services: [
      { name: "Full Glam Makeup", price: 20000, duration: "1.5 hrs" },
      { name: "Natural / Soft Glam", price: 12000, duration: "1 hr" },
      { name: "Bridal Makeup", price: 40000, duration: "2 hrs" },
    ],
    reviews: [
      {
        author: "Kemi F.",
        rating: 5,
        text: "Shade did my makeup for my wedding and I got SO many compliments. Will use her forever.",
        date: "3 days ago",
      },
      {
        author: "Ngozi B.",
        rating: 4,
        text: "Very professional and her kit is well-stocked. My glam was flawless for the owambe.",
        date: "1 week ago",
      },
    ],
  },
  {
    id: "g3",
    name: "Ngozi Philips",
    slug: "ngozi-philips",
    avatar: null,
    initials: "NP",
    headline: "Nail technician · Gel, acrylic & nail art",
    specialties: ["Gel Nails", "Acrylics", "Nail Art"],
    categories: ["NAILS"],
    zones: ["Ikeja", "Surulere", "Yaba"],
    avgRating: 4.8,
    reviewCount: 156,
    totalJobs: 212,
    isOnline: false,
    isVerified: true,
    bio: "I do nails that last. Certified nail tech with 4 years of experience. I bring my full UV setup and all the gel colours you can think of.",
    baseRate: 8000,
    services: [
      { name: "Gel Nails", price: 8000, duration: "1.5 hrs" },
      { name: "Acrylic Nails", price: 10000, duration: "1.5 hrs" },
      { name: "Manicure & Pedicure", price: 6000, duration: "1 hr" },
    ],
    reviews: [
      {
        author: "Adaeze I.",
        rating: 5,
        text: "My nails lasted 5 weeks! Ngozi does such clean work.",
        date: "4 days ago",
      },
    ],
  },
  {
    id: "g4",
    name: "Emeka Okafor",
    slug: "emeka-okafor",
    avatar: null,
    initials: "EO",
    headline: "Barber · Fades, shape-ups & beard grooming",
    specialties: ["Haircut & Fade", "Beard", "Shape-up"],
    categories: ["BARBING"],
    zones: ["Yaba", "Surulere", "Lekki"],
    avgRating: 4.8,
    reviewCount: 198,
    totalJobs: 314,
    isOnline: true,
    isVerified: true,
    bio: "Fresh cuts delivered to your door. I bring my full kit — clippers, razors, the works. No waiting, no traffic.",
    baseRate: 4000,
    services: [
      { name: "Haircut & Fade", price: 4000, duration: "45 min" },
      { name: "Shape-Up & Lining", price: 2500, duration: "30 min" },
      { name: "Beard Grooming", price: 3000, duration: "30 min" },
    ],
    reviews: [
      {
        author: "Tunde A.",
        rating: 5,
        text: "Emeka is the best barber I've used at home. Clean fade, no mess.",
        date: "1 day ago",
      },
    ],
  },
  {
    id: "g5",
    name: "Blessing Taiwo",
    slug: "blessing-taiwo",
    avatar: null,
    initials: "BT",
    headline: "Lash tech · Classic, volume & lash lifts",
    specialties: ["Classic Lashes", "Volume", "Lash Lift"],
    categories: ["LASHES"],
    zones: ["VI", "Lekki", "Ikoyi"],
    avgRating: 4.6,
    reviewCount: 89,
    totalJobs: 113,
    isOnline: false,
    isVerified: true,
    bio: "Certified lash technician. I use only premium, cruelty-free materials. My lashes last 3–5 weeks with proper aftercare.",
    baseRate: 12000,
    services: [
      { name: "Classic Lash Extensions", price: 12000, duration: "1.5 hrs" },
      { name: "Volume Lashes", price: 18000, duration: "2 hrs" },
      { name: "Lash Lift & Tint", price: 8000, duration: "1 hr" },
    ],
    reviews: [],
  },
];

export const ZONES = [
  "Victoria Island",
  "Lekki Phase 1",
  "Ikoyi",
  "Oniru",
  "Ikeja",
  "Surulere",
  "Yaba",
  "Ajah",
  "Gbagada",
  "Magodo",
];

export const TRUST_STATS = [
  { value: "50+", label: "Vetted groomers" },
  { value: "< 45 min", label: "Avg. arrival time" },
  { value: "24/7", label: "Always available" },
  { value: "4.8★", label: "Average rating" },
];
